language: go
sudo: required

go:
  - 1.10.x
  - tip

service:
  - docker

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

go_import_path: github.com/src-d/regression-borges

script:
  - wget https://github.com/src-d/borges/releases/download/v0.18.1/borges_v0.18.1_linux_amd64.tar.gz -O /tmp/borges.tar.gz
  - tar xf /tmp/borges.tar.gz borges_linux_amd64/borges
  - export PATH=$PWD/borges_linux_amd64:$PATH
  - make dependencies
  - make test-coverage

before_deploy:
  - make packages

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: build/*.tar.gz
  skip_cleanup: true
  on:
    tags: true

after_deploy:
  - DOCKER_PUSH_LATEST=1 make docker-push
